name: Build

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up CMake
        uses: lukka/get-cmake@latest

      - name: Build
        run: |
          mkdir build
          cmake -S . -B build -DFLAG_BUILD_TESTS=OFF
          cmake --build build
        shell: bash

      - name: Upload
        uses: actions/upload-artifact@v4
        with:
          name: MyProject-${{ matrix.os }}
          path: build/MyProject*

    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
